AMCE/urls.py
from django.contrib import admin
from django.urls import include, path
from AMCE.forms import CustomAuthForm
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

#se agrega para heroku
#from django.conf import settings 
#from django.conf.urls.static import static

# Views
import AMCE.views as views

app_name = "AMCE"
urlpatterns = [
#URLS CRECIÓN DE TIPOS DE USUARIOS
path('estudiante/vistaEstudiante/', views.vistaAlumno, name = 'vistaAlumno'),
path('profesor/vistaProfesor/', views.vistaProfesor, name = 'vistaProfesor'),
# URLS COMPARTIDAS
path('', views.index, name = 'index'),
path('registro/', views.signup, name = 'signup'),
path('registro/estudiante/', views.EstSignup.as_view(), name='EstSignup'),
path('registro/profesor/', views.ProfSignup.as_view(), name='ProfSignup'),
path('test_password', views.password_validation, name='test_password'),



# Recuperación de contraseñas
path('password_reset', 
    auth_views.PasswordResetView.as_view(
        template_name = 'registration/reset_password.html', 
        email_template_name = 'registration/reset_password_email.html', #me servira para el diseño del correo
        success_url = reverse_lazy('AMCE:password_reset_done')), 
    name='reset_password'),
path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name = 'registration/reset_password_sent.html'), name='password_reset_done'),
path('reset/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(
        template_name = 'registration/reset_password_form.html',
        success_url = reverse_lazy('AMCE:password_reset_complete')), name='password_reset_confirm'),
path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_password_done.html'), name='password_reset_complete'),

# URLS ESTUDIANTE
path('estudiante/MisGrupos/', views.EstMisGrupos, name = 'EstMisGrupos'),
path('estudiante/InscribirGrupo/', views.EstInscribirGrupo, name = 'EstInscribirGrupo'),
path('estudiante/Grupo/<str:id_grupo>/', views.EstPaginaGrupo, name = 'EstPaginaGrupo'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/actividad/aviso', views.AvisoNoContinuar, name = 'AvisoNoContinuar'),

path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/', views.AnalisisPreguntaInicial, name = 'AnalisisPreguntaInicial'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/', views.postPreguntaInicial, name = 'PreguntaInicial'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/actividad/aviso', views.AvisoNoContinuarAnalisis, name = 'AvisoNoContinuarAnalisis'), 
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/FeedPreguntaInicial/', views.feedPIHecha, name = 'feedPIHecha'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/DefiniciónPreguntaInicial/', views.defPreguntaInicial, name = 'defPreguntaInicial'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/', views.PreguntasSecundarias, name = 'PreguntasSecundarias'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/actividad/aviso', views.PSAvisoNoContinuar, name = 'PSAvisoNoContinuar'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación', views.EvaluacionPS, name = 'EvaluacionPS'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación/evaluacionsecundarias', views.EvaluacionPreSec, name = 'EvaluacionPreSec'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación/aviso', views.AvisoNoContinuarEvaPS, name = 'AvisoNoContinuarEvaPS'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación/actividad/plandeevaluación', views.PlanDeInvestigacion, name = 'PlanDeInvestigacion'),


# URLS ESTUDIANTE Paso 2
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/fuentes', views.seleccionaFuentes, name = "seleccionFuentes"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/<str:definirFuente>/nueva-fuente', views.FuenteCreateView.as_view(), name = 'CrearFuenteView'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/editar-fuente/<pk>', views.FuenteUpdateView.as_view(), name = 'FuenteUpdateView'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/eliminar-fuente/<pk>', views.FuenteDeleteView.as_view(), name = 'FuenteDeleteView'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/instrucciones-evaluar-fuentes', views.instuccionesNuevaFuente, name = 'instuccionesNuevaFuente'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes', views.evaluarFuentes, name = "evaluarFuentes"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes/aviso', views.AvisoNoContinuarEvaFuentes, name = "AvisoNoContinuarEvaFuentes"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes/aviso2', views.AvisoNoContinuarEvaFuentes2, name = "AvisoNoContinuarEvaFuentes2"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes/PlanDeInvestigaciónPaso2', views.EvaluarFuentesPlanInvestigación, name = "EvaluarFuentesPlanInvestigación"),


path('estudiante/RePreguntaInicial', views.RePreguntaInicial, name = "RePreguntaInicial"),
path('estudiante/RePreguntasSecundarias', views.RePreguntasSecundarias, name = "RePreguntasSecundarias"),
path('estudiante/AnexoProducto', views.AnexoProducto, name = "AnexoProducto"),
path('estudiante/CuestionarioEvaluacion', views.CuestionarioEvaluacion, name = "CuestionarioEvaluacion"),




# URLS PROFESOR
path('profesor/MisGrupos/', views.ProfMisGrupos, name = 'ProfMisGrupos'),
path('profesor/CrearGrupo/', views.ProfCrearGrupo, name = 'ProfCrearGrupo'),
path('profesor/EditarGrupo/<str:id_grupo>', views.ProfEditarGrupo, name = 'ProfEditarGrupo'),
path('profesor/EliminarGrupo/<str:id_grupo>', views.ProfEliminarGrupo, name = 'ProfEliminarGrupo'),
path('profesor/Grupo/<str:id_grupo>/', views.ProfPaginaGrupo, name = 'ProfPaginaGrupo'),
path('profesor/Grupo/<str:id_grupo>/CrearEquipo/', views.ProfCrearEquipo, name = 'ProfCrearEquipo'),
path('profesor/Grupo/<str:id_grupo>/Equipo/<int:id_equipo>/', views.ProfPaginaEquipo, name = 'ProfPaginaEquipo'),
path('profesor/Grupo/<str:id_grupo>/AsignarTema/', views.ProfAsignarTemaGrupo, name = 'ProfAsignarTemaGrupo'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/', views.ProfTemaAsignado, name = 'ProfTemaAsignado'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/ProgresoGrupo', views.ProfProgresoGrupo, name = 'ProfProgresoGrupo'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/Equipo/<int:id_equipo>', views.ProfProgresoEquipo, name = 'ProfProgresoEquipo'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/Equipo/<int:id_equipo>/Retro/<int:paso>', views.ProfRetro, name = 'ProfRetro'),
path('profesor/MisTemas/', views.ProfMisTemas, name = 'ProfMisTemas'),
path('profesor/CrearTema/', views.ProfCrearTema, name = 'ProfCrearTema')
]

TesisImp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#Importamos las vistas de la aplicación django AMCE
from AMCE import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("AMCE.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += staticfiles_urlpatterns()

AMCE/forms.py
from gettext import translation
from django import forms 
from re import U
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.forms.widgets import PasswordInput, TextInput
from django.db import transaction
from django.db.models import Count

from django.utils.translation import gettext_lazy as _

from .models import *

DUMMY_CHOICES =(
	("1", "Placeholder"),
	("2", "Placeholder"),
)

class CustomAuthForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthForm, self).__init__(*args, **kwargs)
		
    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Nombre de Usuario', 'id': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Contraseña',
            'id': 'password',
        }
	))

class EstSignupForm(UserCreationForm):
	
	class Meta(UserCreationForm):
		model = User
		fields = ['username', "first_name", "last_name", "email", "password1", "password2"]

	def save(self):
		user = super().save(commit=False)
		user.es_estudiante = True
		user.save()
		estudiante = Estudiante.objects.create(user_estudiante=user)
		return user

class FormInscribirGrupo(forms.Form):
	#Form el cual se usa para poder capturar un código de matería/clase dado por el profesor
	codigo = forms.CharField(label='Ingresa el código de la clase', max_length = 10)


class PreguntaInicial(forms.Form):
	#Form que captura la pregunta inicial de paso 1.1 del Modelo Gavilán
	contenido = forms.CharField(label='', max_length = 500, widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu pregunta inicial'}))


class RetroalimentacionPI(forms.Form):
	#Form que captura la pregunta inicial de paso 1.1 del Modelo Gavilán
	contenido = forms.CharField(label='', max_length = 500, widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu comentario'}))

# FORMS PROFESOR

class ProfSignupForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		model = User
		fields = ['username', "first_name", "last_name", "email", "password1", "password2"]
	
	def save(self, commit=True):
		user = super().save(commit=False)
		user.es_profesor = True
		if commit:
			user.save()
		profesor = Profesor.objects.create(user_profesor=user)
		return user
class FormGrupo(ModelForm):
	class Meta:
		model = Grupo
		fields = ['nombre_grupo', 'materia', 'institucion']
		labels = {
            'nombre_grupo': _('Nombre del grupo')
        }

class FormTema(ModelForm):
	class Meta:
		model = Tema
		fields = ['nombre_tema']
		labels = {
            'nombre_tema': _('Nombre del tema')
        }


class FormCrearEquipo(forms.Form):
	nombre_equipo = forms.CharField(label='Nombre del equipo',max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
	integrantes = forms.ModelMultipleChoiceField(queryset=Estudiante.objects.all(), required=True, widget=forms.SelectMultiple)
	
	def clean_integrantes(self):
		value = self.cleaned_data['integrantes']
		if len(value) > 4 or len(value) < 2:
			raise forms.ValidationError("Los equipos deben de tener de 2 a 4 integrantes.")
		return value

class AsignarTemaGrupo(forms.Form):
	tema = forms.ModelChoiceField(queryset=Tema.objects.all(), empty_label=None, required=True, widget=forms.Select(attrs={'class': 'form-select'}))
	equipos = forms.ModelMultipleChoiceField(queryset=Equipo.objects.all(), required=True, widget=forms.SelectMultiple)
	preguntas_secundarias = forms.IntegerField(label='Número de preguntas secundarias por alumno', min_value=1, widget= forms.TextInput(attrs={'class': 'form-control'}))
	fuentes = forms.IntegerField(label='Número de fuentes por alumno', min_value=1, widget= forms.TextInput(attrs={'class': 'form-control'}))
	def __init__(self,*args,**kwargs):
		id_grupo = ''
		if 'id_grupo' in kwargs.keys():
			id_grupo = kwargs.pop('id_grupo')
		super().__init__(*args, **kwargs)
		if id_grupo != '':
			user_id = Grupo.objects.get(id_grupo=id_grupo).profesor_grupo
			temas = Tema.objects.filter(profesor_tema=user_id)
			equipos = Equipo.objects.filter(grupo_equipo=id_grupo)
			self.fields['equipos'].queryset = equipos
			self.fields['tema'].queryset = temas


class FormRetro(forms.Form):
	retro = forms.CharField(label='Comentarios', widget=forms.Textarea(attrs={'class': 'form-control'}))
'''
#Heredo del userCreationForm que viene en django
class CustomUserCreationForm(UserCreationForm):
	
	#Forms el cual se usa para la creación de un usuario nuevo, su uso se ve refejado en la base de
	#datos del modelo User que tiene django por defecto
	
	class Meta:
		#Se define que es el modelo User el cual se le agregaran los datos capturados
		model = User
		fields = ['username', "first_name", "last_name", "email", "password1", "password2"]

class FormInscribirGrupo(forms.Form):
	
	#Form el cual se usa para poder capturar un código de matería/clase dado por el profesor
	
	codigo = forms.CharField(label='Ingresa el código de la clase', max_length = 10)

class FormActividadPI(forms.Form):
	
	#Form que captura la pregunta inicial de paso 1.1 del Modelo Gavilán
	
	contenido = forms.CharField(label='', max_length = 500, widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu pregunta inicial'}))

#FORM EN ETAPA DE PRUEBA
class PostPreguntaInicial(forms.ModelForm):
	#Aqui se obtiene el campo de contenido de nuestro modelo Forms para Post
	content = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu pregunta inicial'}))

	class Meta:
		model = Post
		fields = ['content']
'''


class NuevaFuenteForm(forms.Form):

	TIPO_FUENTE_CHOISES = (
        ('0', 'LIBRO'),
        ('1', 'REVISTA'),
        ('2', 'PERIODICO'),
        ('3', 'SITIO WEB'),
        ('4', 'VIDEO'),
        ('5', 'IMAGEN')
    )
	TIPO_RECURSO_CHOISES = (
        ('0', 'ARCHIVO'),
        ('1', 'ENLACE'),
    )

	titulo = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ingrese el título', 'class': 'form-control'}))
	autor = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ingrese el autor', 'class': 'form-control'}))
	fecha_publicacion = forms.CharField(widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}))
	lugar = forms.CharField(widget=forms.TextInput(attrs={ 'placeholder': 'Ingrese el lugar de publicación', 'class': 'form-control'}))
	tipo_fuente = forms.ChoiceField(choices=TIPO_FUENTE_CHOISES, widget=forms.Select(attrs={'class': 'form-select'}))
	tipo_recurso = forms.ChoiceField(choices=TIPO_RECURSO_CHOISES, widget=forms.Select(attrs={'class': 'form-select'}))
	enlace = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ingrese un enlace', 'class': 'form-control'}))


class EditFuenteForm(forms.ModelForm):

    class Meta:
        model = Fuente
        fields = (
			'titulo',
			'autor',
			'fecha_publicacion',
			'lugar',
			'tipo_fuente',
			'tipo_recurso',
			'enlace',
        )

        widgets = {
            'titulo': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese el título',
					'class': 'form-control',
                }
            ),
			'autor': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese el autor',
					'class': 'form-control',
                }
            ),
			'fecha_publicacion': forms.DateInput(
               format='%Y-%m-%d', attrs={'type': 'date'}
			),
			'lugar': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese el lugar de publicación',
					'class': 'form-control',
                }
            ),
			'enlace': forms.TextInput(
                attrs={
					'id': 'enlace',
                    'placeholder': 'Ingrese el enlace',
					'class': 'form-control',
                }
            ),
			'tipo_recurso': forms.Select(
				attrs={
					'class': 'form-select'
				}
			),
			'tipo_fuente': forms.Select(
				attrs={
					'class': 'form-select'
				}
			)
			
        }

class EvaluarFuente(forms.Form):
	#Form que captura la pregunta inicial de paso 1.1 del Modelo Gavilán
	contenido = forms.CharField(label='', max_length = 700, widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Argumenta el por qué seleccionaste esa fuente'}))

AMCE/views/compartidas.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..forms import *
from django.contrib.auth import authenticate, login
from django.template import RequestContext
from django.contrib.auth.models import User
from ..models import *
from django.urls import reverse

def index(request):
	if request.method == 'POST':
		form = CustomAuthForm(data=request.POST)
		if form.is_valid():
			user = authenticate(username=form.cleaned_data["username"], password=form.cleaned_data["password"])
			print(user)
			if user is not None:
				login(request,user)
				if user.es_estudiante:
					return redirect('AMCE:vistaAlumno')
				elif user.es_profesor:
					return redirect('AMCE:ProfMisGrupos')
	else:
		form = CustomAuthForm()
	return render(request,'index.html',{"form": form})

def signup(request):
	return render(request,"registration/signup.html")

def password_validation(request):
	return render(request,"registration/test_pass_validation.html")

"""
@csrf_exempt
def password_validation(request):
 
    valid = False
    min_strength = settings.PASSWORD_MINIMUM_ENTROPY
 
    if request.method == 'GET':
        password = request.GET["password"]
        results = password_strength(password)
 
        if results['entropy'] > min_strength:
            valid = True
 
        return JsonResponse({
            'valid': valid,
            'min_strength': min_strength,
            'results': results}
            )
"""
	

AMCE/templates/profesor/AsignarTemaGrupo.html
{% extends "profesor/base_formpage.html" %}

{% load static %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/multiselect.css'%}"/>
    <link rel="stylesheet" href="{% static 'css/AsignarTemaGrupo.css'%}"/>
    <script src="{%static 'js/multiselect.min.js' %}"></script>
{% endblock %}

{% block title %}
    Asignar Tema
{% endblock %}

{% block navbar-title %}
    Asignar Tema
{% endblock %}

{% block button_content %}
    Asignar
{% endblock %}

{% block scripts %}
    <script>
        document.multiselect('#id_equipos');
    </script>
{% endblock %}

AMCE/templates/profesor/CrearEquipo.html
{% extends "profesor/base_formpage.html" %}

{% load static %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/multiselect.css'%}"/>
    <script src="{%static 'js/multiselect.min.js' %}"></script>
{% endblock %}

{% block title %}
    Crear Equipo
{% endblock %}

{% block navbar-title %}
    Crear Equipo
{% endblock %}

{% block button_content %}
    Guardar
{% endblock %}

{% block scripts %}
    <script>
        document.multiselect('#id_integrantes');
    </script>
{% endblock %}

AMCE/templates/profesor/MisGrupos.html
{% extends "profesor/base_mainpage.html" %}

{% load static %}

{% block title %}
    Mis Grupos
{% endblock %}

{% block navbar-title %}
    Mis Grupos
{% endblock %}

{% block navbar-btn %}
    <a class="navbar-nav me-2 nav-bar-btn" href="{% url 'AMCE:ProfCrearGrupo' %}" id="inscribir_grupo"> <img
    src="{% static 'assets/images/bt_grupos.png'%}"></a>
{% endblock %}

{% block grupos-active %}
    active
{% endblock %}

{% block inner_content %}
    <div class="gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 mx-3 justify-content group-card-format">
        <!--Grupos-->
        {% for g in grupos %}
        <div class="mt-2">
            <!-- Detalles del grupo -->
            <div class="group-card position-relative">
                <p class="m-0"><b>Grupo:</b> {{g.nombre_grupo}}</p>
                <p class="m-0"><b>Materia:</b> {{g.materia}}</p>
                <p class="m-0"><b>Institución:</b> {{g.institucion}}</p>
                <p class="m-0 mt-2"><b>Código:</b> {{g.id_grupo}}</p>
                
                <a class="" href="{% url 'AMCE:ProfEditarGrupo' id_grupo=g.id_grupo %}">
                    <img class="mis-grupos-edit" src="{% static 'assets/images/bt_editar.png'%}" alt="">
                </a>
                <a class="" href="{% url 'AMCE:ProfPaginaGrupo' id_grupo=g.id_grupo %}">
                    <svg class="mis-grupos-view" clip-rule="evenodd" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m11.998 5c-4.078 0-7.742 3.093-9.853 6.483-.096.159-.145.338-.145.517s.048.358.144.517c2.112 3.39 5.776 6.483 9.854 6.483 4.143 0 7.796-3.09 9.864-6.493.092-.156.138-.332.138-.507s-.046-.351-.138-.507c-2.068-3.403-5.721-6.493-9.864-6.493zm8.413 7c-1.837 2.878-4.897 5.5-8.413 5.5-3.465 0-6.532-2.632-8.404-5.5 1.871-2.868 4.939-5.5 8.404-5.5 3.518 0 6.579 2.624 8.413 5.5zm-8.411-4c2.208 0 4 1.792 4 4s-1.792 4-4 4-4-1.792-4-4 1.792-4 4-4zm0 1.5c-1.38 0-2.5 1.12-2.5 2.5s1.12 2.5 2.5 2.5 2.5-1.12 2.5-2.5-1.12-2.5-2.5-2.5z" fill-rule="nonzero"/></svg>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

AMCE/templates/profesor/PaginaGrupo.html
{% extends "profesor/base_mainpage.html" %}

{% load static %}

{% block title %}
    Grupo: {{ grupo }}
{% endblock %}

{% block navbar-title %}
    Grupo: {{ grupo }}
{% endblock %}

{% block inner_content %}
    <ul class="nav nav-pills nav-justified" id="tabsGrupo" role="tablist">
        <li class="nav-item me-2 h4" role="presentation">
            <button class="nav-link {% if not redirect %}active{% endif %}" id="temas-tab" data-bs-toggle="tab" data-bs-target="#temas" type="button" role="tab" aria-controls="temas" aria-selected="true">Temas Asignados</button>
        </li>
        <li class="nav-item ms-2 h4" role="presentation">
            <button class="nav-link {% if redirect %}active{% endif %}" id="equipos-tab" data-bs-toggle="tab" data-bs-target="#equipos" type="button" role="tab" aria-controls="equipos" aria-selected="false">Equipos</button>
        </li>
    </ul>
    <div class="tab-content px-4">
        <div class="tab-pane fade {% if not redirect %}show active{% endif %}" id="temas" role="tabpanel" aria-labelledby="temas-tab">
   
            <a class="button-format w-full mt-5"  href="{% url 'AMCE:ProfAsignarTemaGrupo' id_grupo=id_grupo %}" id="asignar_tema">Asignar Tema</a>
            
            <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 justify-content mt-5">
                {% for t in temas %}
                <div class="col mb-4">
                    <a href="{% url 'AMCE:ProfTemaAsignado' id_grupo=id_grupo id_tema=t.id_tema%}">
                        <div class="card h-100" >
                            <!-- Detalles del tema -->
                            <div class="card-body p-4">
                                <div>
                                    <h2 class="m-0 text-center">{{t.nombre_tema}}</h2>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="tab-pane fade {% if redirect %}show active{% endif %}" id="equipos" role="tabpanel" aria-labelledby="equipos-tab">
            </br>
            </br>
            <a class="button-format w-full"   href="{% url 'AMCE:ProfCrearEquipo' id_grupo=id_grupo %}" id="crear_equipo">Crear Equipo</a>
            </br>
            </br>
            <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 justify-content">
                {% for e in equipos %}
                <div class="col mb-4">
                    <a href="{% url 'AMCE:ProfPaginaEquipo' id_grupo=id_grupo id_equipo=e.id_equipo%}">
                        <div class="card h-100">
                            <div class="card-body p-4">
                                <div>
                                    <h2 class="m-0 text-center">{{ e.nombre_equipo }}</h2>
                                </div>
                            </div>
                        </div>
                    </a>
                    
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

AMCE/templates/profesor/TemaAsignado.html
{% extends "profesor/base_mainpage.html" %}

{% load static %}

{% block title %}
    Tema Asignado: {{ grupo }} - {{ tema }}
{% endblock %}

{% block navbar-title %}
    Tema Asignado: {{ grupo }} - {{ tema }}
{% endblock %}

{% block inner_content %}
    <a class="button-format w-full" href="{% url 'AMCE:ProfProgresoGrupo' id_grupo=grupo.id_grupo id_tema=tema.id_tema %}">Ver progreso de todos los equipos</a>
    <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 justify-content">
        <!--Equipos-->
        {% for e in equipos %}
        <div class="col mt-4">
            <a href="{% url 'AMCE:ProfProgresoEquipo' id_grupo=grupo.id_grupo id_tema=tema.id_tema id_equipo=e.id_equipo %}">
                <div class="card h-100" >
                    <!-- Detalles del tema -->
                    <div class="card-body p-4">
                        <div>
                            <h2 class="m-0 text-center">{{e.nombre_equipo}}</h2>
                        </div>
                    </div>
                </div>


            </a>
        </div>
        {% endfor %}
    </div>
{% endblock %}

AMCE/templates/profesor/base_mainpage.html
{% extends "profesor/base.html" %}

{% load static %}

{% block content %}
    {% block inner_content %}

    {% endblock %}
{% endblock %}

AMCE/templates/profesor/vistaProfesor.html
<html>
    <head>

    </head>
    <body>
        <h1>Esto es una vista para el profesor</h1>
    </body>
</html>