AMCE/urls.py
from django.contrib import admin
from django.urls import include, path
from AMCE.forms import CustomAuthForm
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

#se agrega para heroku
#from django.conf import settings 
#from django.conf.urls.static import static

# Views
import AMCE.views as views

app_name = "AMCE"
urlpatterns = [
#URLS CRECIÓN DE TIPOS DE USUARIOS
path('estudiante/vistaEstudiante/', views.vistaAlumno, name = 'vistaAlumno'),
path('profesor/vistaProfesor/', views.vistaProfesor, name = 'vistaProfesor'),
# URLS COMPARTIDAS
path('', views.index, name = 'index'),
path('registro/', views.signup, name = 'signup'),
path('registro/estudiante/', views.EstSignup.as_view(), name='EstSignup'),
path('registro/profesor/', views.ProfSignup.as_view(), name='ProfSignup'),
path('test_password', views.password_validation, name='test_password'),



# Recuperación de contraseñas
path('password_reset', 
    auth_views.PasswordResetView.as_view(
        template_name = 'registration/reset_password.html', 
        email_template_name = 'registration/reset_password_email.html', #me servira para el diseño del correo
        success_url = reverse_lazy('AMCE:password_reset_done')), 
    name='reset_password'),
path('reset_password_sent', auth_views.PasswordResetDoneView.as_view(template_name = 'registration/reset_password_sent.html'), name='password_reset_done'),
path('reset/<uidb64>/<token>/', 
    auth_views.PasswordResetConfirmView.as_view(
        template_name = 'registration/reset_password_form.html',
        success_url = reverse_lazy('AMCE:password_reset_complete')), name='password_reset_confirm'),
path('reset_password_complete', auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_password_done.html'), name='password_reset_complete'),

# URLS ESTUDIANTE
path('estudiante/MisGrupos/', views.EstMisGrupos, name = 'EstMisGrupos'),
path('estudiante/InscribirGrupo/', views.EstInscribirGrupo, name = 'EstInscribirGrupo'),
path('estudiante/Grupo/<str:id_grupo>/', views.EstPaginaGrupo, name = 'EstPaginaGrupo'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/actividad/aviso', views.AvisoNoContinuar, name = 'AvisoNoContinuar'),

path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/', views.AnalisisPreguntaInicial, name = 'AnalisisPreguntaInicial'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/', views.postPreguntaInicial, name = 'PreguntaInicial'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/actividad/aviso', views.AvisoNoContinuarAnalisis, name = 'AvisoNoContinuarAnalisis'), 
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/FeedPreguntaInicial/', views.feedPIHecha, name = 'feedPIHecha'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntaInicial/DefiniciónPreguntaInicial/', views.defPreguntaInicial, name = 'defPreguntaInicial'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/', views.PreguntasSecundarias, name = 'PreguntasSecundarias'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/actividad/aviso', views.PSAvisoNoContinuar, name = 'PSAvisoNoContinuar'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación', views.EvaluacionPS, name = 'EvaluacionPS'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación/evaluacionsecundarias', views.EvaluacionPreSec, name = 'EvaluacionPreSec'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación/aviso', views.AvisoNoContinuarEvaPS, name = 'AvisoNoContinuarEvaPS'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/PreguntasSecundarias/evaluación/actividad/plandeevaluación', views.PlanDeInvestigacion, name = 'PlanDeInvestigacion'),


# URLS ESTUDIANTE Paso 2
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/fuentes', views.seleccionaFuentes, name = "seleccionFuentes"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/<str:definirFuente>/nueva-fuente', views.FuenteCreateView.as_view(), name = 'CrearFuenteView'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/editar-fuente/<pk>', views.FuenteUpdateView.as_view(), name = 'FuenteUpdateView'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/eliminar-fuente/<pk>', views.FuenteDeleteView.as_view(), name = 'FuenteDeleteView'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/instrucciones-evaluar-fuentes', views.instuccionesNuevaFuente, name = 'instuccionesNuevaFuente'),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes', views.evaluarFuentes, name = "evaluarFuentes"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes/aviso', views.AvisoNoContinuarEvaFuentes, name = "AvisoNoContinuarEvaFuentes"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes/aviso2', views.AvisoNoContinuarEvaFuentes2, name = "AvisoNoContinuarEvaFuentes2"),
path('estudiante/Grupo/<str:id_grupo>/Tema/<str:id_tema>/EvaluarFuentes/PlanDeInvestigaciónPaso2', views.EvaluarFuentesPlanInvestigación, name = "EvaluarFuentesPlanInvestigación"),


path('estudiante/RePreguntaInicial', views.RePreguntaInicial, name = "RePreguntaInicial"),
path('estudiante/RePreguntasSecundarias', views.RePreguntasSecundarias, name = "RePreguntasSecundarias"),
path('estudiante/AnexoProducto', views.AnexoProducto, name = "AnexoProducto"),
path('estudiante/CuestionarioEvaluacion', views.CuestionarioEvaluacion, name = "CuestionarioEvaluacion"),




# URLS PROFESOR
path('profesor/MisGrupos/', views.ProfMisGrupos, name = 'ProfMisGrupos'),
path('profesor/CrearGrupo/', views.ProfCrearGrupo, name = 'ProfCrearGrupo'),
path('profesor/EditarGrupo/<str:id_grupo>', views.ProfEditarGrupo, name = 'ProfEditarGrupo'),
path('profesor/EliminarGrupo/<str:id_grupo>', views.ProfEliminarGrupo, name = 'ProfEliminarGrupo'),
path('profesor/Grupo/<str:id_grupo>/', views.ProfPaginaGrupo, name = 'ProfPaginaGrupo'),
path('profesor/Grupo/<str:id_grupo>/CrearEquipo/', views.ProfCrearEquipo, name = 'ProfCrearEquipo'),
path('profesor/Grupo/<str:id_grupo>/Equipo/<int:id_equipo>/', views.ProfPaginaEquipo, name = 'ProfPaginaEquipo'),
path('profesor/Grupo/<str:id_grupo>/AsignarTema/', views.ProfAsignarTemaGrupo, name = 'ProfAsignarTemaGrupo'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/', views.ProfTemaAsignado, name = 'ProfTemaAsignado'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/ProgresoGrupo', views.ProfProgresoGrupo, name = 'ProfProgresoGrupo'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/Equipo/<int:id_equipo>', views.ProfProgresoEquipo, name = 'ProfProgresoEquipo'),
path('profesor/Grupo/<str:id_grupo>/Tema/<int:id_tema>/Equipo/<int:id_equipo>/Retro/<int:paso>', views.ProfRetro, name = 'ProfRetro'),
path('profesor/MisTemas/', views.ProfMisTemas, name = 'ProfMisTemas'),
path('profesor/CrearTema/', views.ProfCrearTema, name = 'ProfCrearTema')
]

TesisImp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#Importamos las vistas de la aplicación django AMCE
from AMCE import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("AMCE.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += staticfiles_urlpatterns()

AMCE/forms.py
from gettext import translation
from django import forms 
from re import U
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.forms.widgets import PasswordInput, TextInput
from django.db import transaction
from django.db.models import Count

from django.utils.translation import gettext_lazy as _

from .models import *

DUMMY_CHOICES =(
	("1", "Placeholder"),
	("2", "Placeholder"),
)

class CustomAuthForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthForm, self).__init__(*args, **kwargs)
		
    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Nombre de Usuario', 'id': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Contraseña',
            'id': 'password',
        }
	))

class EstSignupForm(UserCreationForm):
	
	class Meta(UserCreationForm):
		model = User
		fields = ['username', "first_name", "last_name", "email", "password1", "password2"]

	def save(self):
		user = super().save(commit=False)
		user.es_estudiante = True
		user.save()
		estudiante = Estudiante.objects.create(user_estudiante=user)
		return user

class FormInscribirGrupo(forms.Form):
	#Form el cual se usa para poder capturar un código de matería/clase dado por el profesor
	codigo = forms.CharField(label='Ingresa el código de la clase', max_length = 10)


class PreguntaInicial(forms.Form):
	#Form que captura la pregunta inicial de paso 1.1 del Modelo Gavilán
	contenido = forms.CharField(label='', max_length = 500, widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu pregunta inicial'}))


class RetroalimentacionPI(forms.Form):
	#Form que captura la pregunta inicial de paso 1.1 del Modelo Gavilán
	contenido = forms.CharField(label='', max_length = 500, widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu comentario'}))

# FORMS PROFESOR

class ProfSignupForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		model = User
		fields = ['username', "first_name", "last_name", "email", "password1", "password2"]
	
	def save(self, commit=True):
		user = super().save(commit=False)
		user.es_profesor = True
		if commit:
			user.save()
		profesor = Profesor.objects.create(user_profesor=user)
		return user
class FormGrupo(ModelForm):
	class Meta:
		model = Grupo
		fields = ['nombre_grupo', 'materia', 'institucion']
		labels = {
            'nombre_grupo': _('Nombre del grupo')
        }

class FormTema(ModelForm):
	class Meta:
		model = Tema
		fields = ['nombre_tema']
		labels = {
            'nombre_tema': _('Nombre del tema')
        }


class FormCrearEquipo(forms.Form):
	nombre_equipo = forms.CharField(label='Nombre del equipo',max_length=100, widget= forms.TextInput(attrs={'class': 'form-control'}))
	integrantes = forms.ModelMultipleChoiceField(queryset=Estudiante.objects.all(), required=True, widget=forms.SelectMultiple)
	
	def clean_integrantes(self):
		value = self.cleaned_data['integrantes']
		if len(value) > 4 or len(value) < 2:
			raise forms.ValidationError("Los equipos deben de tener de 2 a 4 integrantes.")
		return value

class AsignarTemaGrupo(forms.Form):
	tema = forms.ModelChoiceField(queryset=Tema.objects.all(), empty_label=None, required=True, widget=forms.Select(attrs={'class': 'form-select'}))
	equipos = forms.ModelMultipleChoiceField(queryset=Equipo.objects.all(), required=True, widget=forms.SelectMultiple)
	preguntas_secundarias = forms.IntegerField(label='Número de preguntas secundarias por alumno', min_value=1, widget= forms.TextInput(attrs={'class': 'form-control'}))
	fuentes = forms.IntegerField(label='Número de fuentes por alumno', min_value=1, widget= forms.TextInput(attrs={'class': 'form-control'}))
	def __init__(self,*args,**kwargs):
		id_grupo = ''
		if 'id_grupo' in kwargs.keys():
			id_grupo = kwargs.pop('id_grupo')
		super().__init__(*args, **kwargs)
		if id_grupo != '':
			user_id = Grupo.objects.get(id_grupo=id_grupo).profesor_grupo
			temas = Tema.objects.filter(profesor_tema=user_id)
			equipos = Equipo.objects.filter(grupo_equipo=id_grupo)
			self.fields['equipos'].queryset = equipos
			self.fields['tema'].queryset = temas


class FormRetro(forms.Form):
	retro = forms.CharField(label='Comentarios', widget=forms.Textarea(attrs={'class': 'form-control'}))
'''
#Heredo del userCreationForm que viene en django
class CustomUserCreationForm(UserCreationForm):
	
	#Forms el cual se usa para la creación de un usuario nuevo, su uso se ve refejado en la base de
	#datos del modelo User que tiene django por defecto
	
	class Meta:
		#Se define que es el modelo User el cual se le agregaran los datos capturados
		model = User
		fields = ['username', "first_name", "last_name", "email", "password1", "password2"]

class FormInscribirGrupo(forms.Form):
	
	#Form el cual se usa para poder capturar un código de matería/clase dado por el profesor
	
	codigo = forms.CharField(label='Ingresa el código de la clase', max_length = 10)

class FormActividadPI(forms.Form):
	
	#Form que captura la pregunta inicial de paso 1.1 del Modelo Gavilán
	
	contenido = forms.CharField(label='', max_length = 500, widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu pregunta inicial'}))

#FORM EN ETAPA DE PRUEBA
class PostPreguntaInicial(forms.ModelForm):
	#Aqui se obtiene el campo de contenido de nuestro modelo Forms para Post
	content = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu pregunta inicial'}))

	class Meta:
		model = Post
		fields = ['content']
'''


class NuevaFuenteForm(forms.Form):

	TIPO_FUENTE_CHOISES = (
        ('0', 'LIBRO'),
        ('1', 'REVISTA'),
        ('2', 'PERIODICO'),
        ('3', 'SITIO WEB'),
        ('4', 'VIDEO'),
        ('5', 'IMAGEN')
    )
	TIPO_RECURSO_CHOISES = (
        ('0', 'ARCHIVO'),
        ('1', 'ENLACE'),
    )

	titulo = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ingrese el título', 'class': 'form-control'}))
	autor = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ingrese el autor', 'class': 'form-control'}))
	fecha_publicacion = forms.CharField(widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}))
	lugar = forms.CharField(widget=forms.TextInput(attrs={ 'placeholder': 'Ingrese el lugar de publicación', 'class': 'form-control'}))
	tipo_fuente = forms.ChoiceField(choices=TIPO_FUENTE_CHOISES, widget=forms.Select(attrs={'class': 'form-select'}))
	tipo_recurso = forms.ChoiceField(choices=TIPO_RECURSO_CHOISES, widget=forms.Select(attrs={'class': 'form-select'}))
	enlace = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ingrese un enlace', 'class': 'form-control'}))


class EditFuenteForm(forms.ModelForm):

    class Meta:
        model = Fuente
        fields = (
			'titulo',
			'autor',
			'fecha_publicacion',
			'lugar',
			'tipo_fuente',
			'tipo_recurso',
			'enlace',
        )

        widgets = {
            'titulo': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese el título',
					'class': 'form-control',
                }
            ),
			'autor': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese el autor',
					'class': 'form-control',
                }
            ),
			'fecha_publicacion': forms.DateInput(
               format='%Y-%m-%d', attrs={'type': 'date'}
			),
			'lugar': forms.TextInput(
                attrs={
                    'placeholder': 'Ingrese el lugar de publicación',
					'class': 'form-control',
                }
            ),
			'enlace': forms.TextInput(
                attrs={
					'id': 'enlace',
                    'placeholder': 'Ingrese el enlace',
					'class': 'form-control',
                }
            ),
			'tipo_recurso': forms.Select(
				attrs={
					'class': 'form-select'
				}
			),
			'tipo_fuente': forms.Select(
				attrs={
					'class': 'form-select'
				}
			)
			
        }

class EvaluarFuente(forms.Form):
	#Form que captura la pregunta inicial de paso 1.1 del Modelo Gavilán
	contenido = forms.CharField(label='', max_length = 700, widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Argumenta el por qué seleccionaste esa fuente'}))

AMCE/views/compartidas.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..forms import *
from django.contrib.auth import authenticate, login
from django.template import RequestContext
from django.contrib.auth.models import User
from ..models import *
from django.urls import reverse

def index(request):
	if request.method == 'POST':
		form = CustomAuthForm(data=request.POST)
		if form.is_valid():
			user = authenticate(username=form.cleaned_data["username"], password=form.cleaned_data["password"])
			print(user)
			if user is not None:
				login(request,user)
				if user.es_estudiante:
					return redirect('AMCE:vistaAlumno')
				elif user.es_profesor:
					return redirect('AMCE:ProfMisGrupos')
	else:
		form = CustomAuthForm()
	return render(request,'index.html',{"form": form})

def signup(request):
	return render(request,"registration/signup.html")

def password_validation(request):
	return render(request,"registration/test_pass_validation.html")

"""
@csrf_exempt
def password_validation(request):
 
    valid = False
    min_strength = settings.PASSWORD_MINIMUM_ENTROPY
 
    if request.method == 'GET':
        password = request.GET["password"]
        results = password_strength(password)
 
        if results['entropy'] > min_strength:
            valid = True
 
        return JsonResponse({
            'valid': valid,
            'min_strength': min_strength,
            'results': results}
            )
"""
	

AMCE/templates/estudiante/2EvaluacionPreguntasSecundarias.html
{% extends "estudiante/base_mainpage.html" %}

{% load static %}

{% block extra-css %}

<style>



</style>

{% endblock %}

{% block title %}
Evaluación Preguntas Secundarias
{% endblock %}

{% block header_ctxt %}
<div class="nav-bar-title navbar-brand ml-3 justify-content-center"> Evaluación <br> preguntas secundarias</div>
<a class=""></a>
{% endblock %}


{% block inner_content %}
<div class="container-content">
  <center>
    <h1 class="mt-4"> Tema: {{ temaNombre }} </h1>
    <h2 class="mt-4"> Pregunta Inicial: {{ pregunta.id_pregunta.contenido }} </h2>
    <h2 class="mb-4 mt-4 "> Evalua las preguntas secundarias de tu equipo </h2>
  </center>
  <form method="post" class="align-items-center">
    {% csrf_token %}
    <div class="w3-container" style="width: 100%;">
      {% for i in preguntasSec %}
      <div >
        <header>
          <table style="width:100%">
            <h3>{{ i.id_pregunta.contenido }}</h3>
            <div class="btn-group btn-group-toggle " style="width: 100%;" data-toggle="buttons">
              <label class="btn btn-secondary button-format active checklist">
                <input type="radio" name="options{{forloop.counter}}" id="megusta" value="3" autocomplete="off"
                  required>
                Me gusta
              </label>
              <label class="btn btn-secondary button-format checklist">
                <input type="radio" name="options{{forloop.counter}}" id="noleentiendo" value="-1" autocomplete="off"
                  required> No le entiendo
              </label>
              <label class="btn btn-secondary button-format checklist">
                <input type="radio" name="options{{forloop.counter}}" id="nomegusta" value="-2" autocomplete="off"
                  required> No me gusta
              </label>
            </div>
          </table>
        </header>
        <br>
      </div>
      {% endfor %}
    </div>

    <div class="mt-2">
      <button type="submit" class="button-format">Continuar al siguiente paso</button>
    </div>
  </form>

</div>

{% endblock %}

{% block scripts %}

<!-- Core theme JS-->
<script src="{%static 'js/MG1.js' %}"></script>
<!-- JS para modal del ingresar código de clase-->
<script src="{%static 'js/modal.js' %}"></script>
{% endblock %}

{% block footer %}
<footer style=" margin-left: 0px;">
  <p style="position: relative; width:100%; left: 0px; bottom: 0; width: 100%;  text-align: center; color: black;">
    &copy; ICAT | UNAM</p>
</footer>
{% endblock %}

AMCE/templates/estudiante/EvFuentesAvisoNoContinuar2.html
{% extends "estudiante/base_formpage.html" %}

{% load static %}

{% block title %}
Aviso
{% endblock %}

{% block header_ctxt %}
<a class="nav-bar-btn" href="{% url 'AMCE:EstMisGrupos' %}" id="inscribir_grupo"> <img
        src="{% static 'assets/images/bt_grupos.png'%}"></a>
{% endblock %}

{% block navbar %}
<a class="navbar-brand" href="{% url 'AMCE:EstMisGrupos' %}"> <i style="color: white; width: 20%; height: 20%;"
        class="bi bi-stopwatch"></i> </a>

{% endblock %}

{% block content %}

<center>
    <div class="text-center wait-warning mw-90">
        <h2>Aviso</h2>
        <p>Tu equipo aún no termina de evaluar las fuentes del equipo, regresa más tarde. </p>
        <center>
            <a name="profesor" class="button-format" href="{% url 'AMCE:EstMisGrupos' %}">Entendido</a>
        </center>
    </div>
</center>

{% endblock content %}


{% block scripts %}
<script>
    $(document).ready(function () { $("#myModal").appendTo("body").modal('show'); });
    $("#myModal").css("z-index", "1500");

</script>
{% endblock %}

AMCE/templates/estudiante/EvPsAvisoNoContinuar.html
{% extends "estudiante/base_formpage.html" %}

{% load static %}

{% block title %}
Aviso
{% endblock %}

{% block header_ctxt %}
<a class="nav-bar-btn" href="{% url 'AMCE:EstMisGrupos' %}" id="inscribir_grupo"> <img
        src="{% static 'assets/images/bt_grupos.png'%}"></a>
{% endblock %}

{% block navbar %}
<a class="navbar-brand" href="{% url 'AMCE:EstMisGrupos' %}"> <i style="color: white; width: 20%; height: 20%;"
        class="bi bi-stopwatch"></i> </a>

{% endblock %}

{% block content %}

<center>
    <div class="text-center wait-warning mw-90 ">
        <h1><b>Aviso</b></h1>
        <p>Tu equipo aún no termina de evaluar las preguntas secundarias, regresa más tarde. </p>
        <center>
            <a name="profesor" class="button-format" href="{% url 'AMCE:EstMisGrupos' %}">Entendido</a>
        </center>
    </div>
</center>

{% endblock content %}


{% block scripts %}
<script>
    $(document).ready(function () { $("#myModal").appendTo("body").modal('show'); });
    $("#myModal").css("z-index", "1500");

</script>
{% endblock %}

AMCE/templates/estudiante/InscribirGrupo.html
{% extends "estudiante/base_formpage.html" %}

{% load static %}


{% block title %}
    Inscribir Grupo
{% endblock %}

{% block header_ctxt %}
    <a class="navbar-brand" href="{% url 'AMCE:EstMisGrupos' %}"><i style="color: white;" class="bi bi-x-lg"></i></a>
    <div class="nav-bar-title navbar-brand ml-3" href="">Inscribir Grupo</div>
{% endblock %}

{% block button_content %}
    Inscribir Grupo
{% endblock %}

AMCE/templates/estudiante/InstruccionesEvaluarFuentes.html
{% extends "estudiante/base_mainpage.html" %}

{% load static %}



{% block extra-css %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Capriola&display=swap%27');
</style>


{% endblock %}

{% block title %}
Seleccion de Fuentes
{% endblock %}

{% block header_ctxt %}
<div class="nav-bar-title navbar-brand ml-3 d-flex w-full justify-content-center"> Busqueda de fuentes</div>
<a class=""></a>
{% endblock %}

{% block inner_content %}

<center class="mt-4">
    <h1>¡Enhorabuena!</h1>
</center>

<div class="container-content">


    <p>Ahora toca evaluar las fuentes seleccionadas por tu equipo </p>

    <p>Para evaluar una fuente proveniente de internet, debes de prestar atención en tres criterios básicos:</p>
    <ul>
        <li>Referencias generales, propiedades y propósitos del sitio web que publica el contenido de la fuente</li>
        <li>Datos sobre el(los) autor(es) de los contenidos</li>
        <li>Caracteristicas de la información que ofrece la fuente y su nivel de confiabilidad y pertinencia para la
            investigación</li>
    </ul>


    <center class="mt-5">
        <a name="profesor" class="button-format"
            href="{% url 'AMCE:evaluarFuentes'  id_grupo=id_grupo id_tema=id_tema %}" id="submit-form">Continuar al
            siguente paso</a>
    </center>

</div>
{% endblock %}



{% block footer %}
<footer style=" margin-left: 0px;">
    <p
        style="font-family: 'Capriola'; position: absolute; width:100%; left: 0px; bottom: 0; width: 100%;  text-align: center; color: black;">
        &copy; ICAT | UNAM</p>
</footer>
{% endblock %}


{% block scripts %}


{% endblock %}

AMCE/templates/estudiante/base_mainpage.html
{% extends "estudiante/base.html" %}

{% load static %}

{% block navbar %}
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
        class="navbar-toggler-icon"></span></button>
<div class="d-flex justify-content-center">
    {% block header_ctxt %}

    {% endblock %}
</div>
<div class="collapse navbar-collapse navbarSupportedContent" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% block navbar_ctxt %}
        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'AMCE:EstMisGrupos' %}">Mis Grupos</a>
        </li>
        {% endblock %}
        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'logout' %}">Cerrar Sesión</a></li>
    </ul>
</div>
{% endblock %}

{% block content %}
    {% block inner_content %}

    {% endblock %}
{% endblock %}

AMCE/templates/estudiante/vistaEstudiante.html
<html>
    <head>

    </head>
    <body>
        <h1>Esto es una vista para el alumno</h1>
    </body>
</html>